#include "extensions/ManifestLoader.h"

#include <cctype>
#include <cstdint>
#include <cstdio>
#include <fstream>
#include <map>
#include <memory>
#include <sstream>
#include <variant>
#include <vector>

namespace ng {
namespace {

// ---- Minimal JSON parser ----------------------------------------------
//
// Hand-rolled because adding a 30 kLOC JSON dependency for a single
// use case isn't worth it, and Manifest V3 files are small + machine-
// generated by extension tooling so the spec subset is well-bounded.
//
// Handles: objects, arrays, strings (with basic escapes including
// \uXXXX), numbers (int + decimal), true / false / null, whitespace.
// Rejects: trailing garbage, unterminated strings, unknown escapes,
// objects with non-string keys.

struct JsonValue;
using JsonObject = std::map<std::string, JsonValue>;
using JsonArray  = std::vector<JsonValue>;

struct JsonValue {
    enum class Kind { Null, Bool, Int, Double, String, Array, Object };
    Kind kind { Kind::Null };
    bool boolValue { false };
    int64_t intValue { 0 };
    double doubleValue { 0.0 };
    std::string stringValue;
    std::shared_ptr<JsonArray>  arrayValue;
    std::shared_ptr<JsonObject> objectValue;

    bool isString() const { return kind == Kind::String; }
    bool isObject() const { return kind == Kind::Object; }
    bool isArray()  const { return kind == Kind::Array; }
    bool isInt()    const { return kind == Kind::Int; }

    const std::string& asString() const { return stringValue; }
    const JsonObject&  asObject() const { return *objectValue; }
    const JsonArray&   asArray()  const { return *arrayValue; }
    int64_t            asInt()    const { return intValue; }

    const JsonValue* find(const std::string& key) const {
        if (!isObject()) return nullptr;
        auto it = objectValue->find(key);
        return it == objectValue->end() ? nullptr : &it->second;
    }
};

class JsonParser {
public:
    explicit JsonParser(const std::string& src) : m_src(src) {}

    Result<JsonValue> parse() {
        skipWhitespace();
        auto v = parseValue();
        if (!v) return Result<JsonValue>::fail(v.error());
        skipWhitespace();
        if (m_pos != m_src.size())
            return failHere("trailing garbage after JSON value");
        return v;
    }

private:
    const std::string& m_src;
    size_t m_pos { 0 };

    Result<JsonValue> parseValue() {
        skipWhitespace();
        if (m_pos >= m_src.size())
            return failHere("unexpected end of input");
        char c = m_src[m_pos];
        switch (c) {
            case '{': return parseObject();
            case '[': return parseArray();
            case '"': return parseString();
            case 't': case 'f': return parseBool();
            case 'n': return parseNull();
            default:
                if (c == '-' || std::isdigit(static_cast<unsigned char>(c)))
                    return parseNumber();
                return failHere("unexpected character");
        }
    }

    Result<JsonValue> parseObject() {
        ++m_pos;  // consume '{'
        auto obj = std::make_shared<JsonObject>();
        skipWhitespace();
        if (peek() == '}') { ++m_pos; JsonValue v; v.kind = JsonValue::Kind::Object; v.objectValue = obj; return Result<JsonValue>::ok(std::move(v)); }
        while (true) {
            skipWhitespace();
            if (peek() != '"') return failHere("expected string key");
            auto keyVal = parseString();
            if (!keyVal) return keyVal;
            skipWhitespace();
            if (peek() != ':') return failHere("expected ':' after key");
            ++m_pos;
            auto v = parseValue();
            if (!v) return v;
            (*obj)[keyVal.value().stringValue] = std::move(v.value());
            skipWhitespace();
            char c = peek();
            if (c == ',') { ++m_pos; continue; }
            if (c == '}') { ++m_pos; break; }
            return failHere("expected ',' or '}' in object");
        }
        JsonValue v; v.kind = JsonValue::Kind::Object; v.objectValue = obj;
        return Result<JsonValue>::ok(std::move(v));
    }

    Result<JsonValue> parseArray() {
        ++m_pos;  // consume '['
        auto arr = std::make_shared<JsonArray>();
        skipWhitespace();
        if (peek() == ']') { ++m_pos; JsonValue v; v.kind = JsonValue::Kind::Array; v.arrayValue = arr; return Result<JsonValue>::ok(std::move(v)); }
        while (true) {
            auto v = parseValue();
            if (!v) return v;
            arr->push_back(std::move(v.value()));
            skipWhitespace();
            char c = peek();
            if (c == ',') { ++m_pos; continue; }
            if (c == ']') { ++m_pos; break; }
            return failHere("expected ',' or ']' in array");
        }
        JsonValue v; v.kind = JsonValue::Kind::Array; v.arrayValue = arr;
        return Result<JsonValue>::ok(std::move(v));
    }

    Result<JsonValue> parseString() {
        if (peek() != '"') return failHere("expected '\"'");
        ++m_pos;
        std::string out;
        while (m_pos < m_src.size()) {
            char c = m_src[m_pos++];
            if (c == '"') {
                JsonValue v; v.kind = JsonValue::Kind::String; v.stringValue = std::move(out);
                return Result<JsonValue>::ok(std::move(v));
            }
            if (c != '\\') { out.push_back(c); continue; }
            if (m_pos >= m_src.size()) return failHere("unterminated escape");
            char esc = m_src[m_pos++];
            switch (esc) {
                case '"':  out.push_back('"');  break;
                case '\\': out.push_back('\\'); break;
                case '/':  out.push_back('/');  break;
                case 'b':  out.push_back('\b'); break;
                case 'f':  out.push_back('\f'); break;
                case 'n':  out.push_back('\n'); break;
                case 'r':  out.push_back('\r'); break;
                case 't':  out.push_back('\t'); break;
                case 'u': {
                    if (m_pos + 4 > m_src.size())
                        return failHere("truncated \\u escape");
                    unsigned cp = 0;
                    for (int i = 0; i < 4; ++i) {
                        char h = m_src[m_pos++];
                        unsigned d;
                        if (h >= '0' && h <= '9') d = h - '0';
                        else if (h >= 'a' && h <= 'f') d = 10 + h - 'a';
                        else if (h >= 'A' && h <= 'F') d = 10 + h - 'A';
                        else return failHere("bad hex in \\u escape");
                        cp = cp * 16 + d;
                    }
                    // UTF-8 encode (BMP only; surrogate pairs left to caller).
                    if (cp < 0x80) out.push_back(static_cast<char>(cp));
                    else if (cp < 0x800) {
                        out.push_back(static_cast<char>(0xC0 | (cp >> 6)));
                        out.push_back(static_cast<char>(0x80 | (cp & 0x3F)));
                    } else {
                        out.push_back(static_cast<char>(0xE0 | (cp >> 12)));
                        out.push_back(static_cast<char>(0x80 | ((cp >> 6) & 0x3F)));
                        out.push_back(static_cast<char>(0x80 | (cp & 0x3F)));
                    }
                    break;
                }
                default: return failHere("unknown escape sequence");
            }
        }
        return failHere("unterminated string");
    }

    Result<JsonValue> parseNumber() {
        size_t start = m_pos;
        if (peek() == '-') ++m_pos;
        while (m_pos < m_src.size() && std::isdigit(static_cast<unsigned char>(m_src[m_pos]))) ++m_pos;
        bool isDouble = false;
        if (m_pos < m_src.size() && m_src[m_pos] == '.') {
            isDouble = true; ++m_pos;
            while (m_pos < m_src.size() && std::isdigit(static_cast<unsigned char>(m_src[m_pos]))) ++m_pos;
        }
        if (m_pos < m_src.size() && (m_src[m_pos] == 'e' || m_src[m_pos] == 'E')) {
            isDouble = true; ++m_pos;
            if (m_pos < m_src.size() && (m_src[m_pos] == '+' || m_src[m_pos] == '-')) ++m_pos;
            while (m_pos < m_src.size() && std::isdigit(static_cast<unsigned char>(m_src[m_pos]))) ++m_pos;
        }
        std::string token = m_src.substr(start, m_pos - start);
        JsonValue v;
        if (isDouble) { v.kind = JsonValue::Kind::Double; v.doubleValue = std::strtod(token.c_str(), nullptr); }
        else          { v.kind = JsonValue::Kind::Int;    v.intValue    = std::strtoll(token.c_str(), nullptr, 10); }
        return Result<JsonValue>::ok(std::move(v));
    }

    Result<JsonValue> parseBool() {
        if (m_src.compare(m_pos, 4, "true") == 0) {
            m_pos += 4; JsonValue v; v.kind = JsonValue::Kind::Bool; v.boolValue = true; return Result<JsonValue>::ok(std::move(v));
        }
        if (m_src.compare(m_pos, 5, "false") == 0) {
            m_pos += 5; JsonValue v; v.kind = JsonValue::Kind::Bool; v.boolValue = false; return Result<JsonValue>::ok(std::move(v));
        }
        return failHere("expected 'true' or 'false'");
    }

    Result<JsonValue> parseNull() {
        if (m_src.compare(m_pos, 4, "null") == 0) { m_pos += 4; return Result<JsonValue>::ok(JsonValue{}); }
        return failHere("expected 'null'");
    }

    void skipWhitespace() {
        while (m_pos < m_src.size()) {
            char c = m_src[m_pos];
            if (c == ' ' || c == '\t' || c == '\n' || c == '\r') ++m_pos;
            else break;
        }
    }

    char peek() const { return m_pos < m_src.size() ? m_src[m_pos] : '\0'; }

    Result<JsonValue> failHere(const char* msg) {
        std::ostringstream out;
        out << "JSON parse error at offset " << m_pos << ": " << msg;
        return Result<JsonValue>::fail({ ErrorCode::InvalidArgument, out.str() });
    }
};

// ---- Manifest extraction ----------------------------------------------

void readStringArray(const JsonValue& src, std::vector<std::string>& out) {
    if (!src.isArray()) return;
    for (const auto& v : src.asArray())
        if (v.isString()) out.push_back(v.asString());
}

}  // namespace

Result<ExtensionManifest> loadManifestFromString(const std::string& json,
                                                 const ExtensionId& extensionId) {
    JsonParser parser(json);
    auto parsed = parser.parse();
    if (!parsed) return Result<ExtensionManifest>::fail(parsed.error());
    if (!parsed.value().isObject())
        return Result<ExtensionManifest>::fail({ ErrorCode::InvalidArgument,
            "manifest.json root must be an object" });

    const JsonObject& root = parsed.value().asObject();
    ExtensionManifest m;
    m.id = extensionId;

    if (auto* mv = parsed.value().find("manifest_version")) {
        if (!mv->isInt() || mv->asInt() != 3)
            return Result<ExtensionManifest>::fail({ ErrorCode::InvalidArgument,
                "only manifest_version 3 is supported" });
        m.version = ExtensionManifestVersion::ManifestV3;
    } else {
        return Result<ExtensionManifest>::fail({ ErrorCode::InvalidArgument,
            "manifest_version is required" });
    }

    if (auto* name = parsed.value().find("name"); name && name->isString())
        m.name = name->asString();
    else
        return Result<ExtensionManifest>::fail({ ErrorCode::InvalidArgument,
            "name is required and must be a string" });

    if (auto* ver = parsed.value().find("version"); ver && ver->isString())
        m.versionString = ver->asString();
    else
        return Result<ExtensionManifest>::fail({ ErrorCode::InvalidArgument,
            "version is required and must be a string" });

    if (auto* perms = parsed.value().find("permissions"))
        readStringArray(*perms, m.permissions);
    if (auto* host = parsed.value().find("host_permissions"))
        readStringArray(*host, m.hostPermissions);

    if (auto* bg = parsed.value().find("background")) {
        if (auto* sw = bg->find("service_worker"); sw && sw->isString())
            m.backgroundServiceWorkers.push_back(sw->asString());
    }

    if (auto* action = parsed.value().find("action")) {
        if (auto* title = action->find("default_title"); title && title->isString())
            m.action.defaultTitle = title->asString();
        if (auto* popup = action->find("default_popup"); popup && popup->isString())
            m.action.defaultPopupPath = popup->asString();
    }

    if (auto* sp = parsed.value().find("side_panel")) {
        if (auto* path = sp->find("default_path"); path && path->isString())
            m.sidePanel.defaultPath = path->asString();
    }

    if (auto* scripts = parsed.value().find("content_scripts");
        scripts && scripts->isArray()) {
        for (const auto& entry : scripts->asArray()) {
            if (!entry.isObject()) continue;
            if (auto* matches = entry.find("matches"))
                readStringArray(*matches, m.contentScriptMatches);
        }
    }

    if (auto v = m.validate(); !v)
        return Result<ExtensionManifest>::fail(v.error());

    (void)root;  // silence "unused" if structured bindings get pruned
    return Result<ExtensionManifest>::ok(std::move(m));
}

Result<ExtensionManifest> loadManifestFromFile(const std::string& manifestPath,
                                               const ExtensionId& extensionId) {
    std::ifstream in(manifestPath, std::ios::binary);
    if (!in)
        return Result<ExtensionManifest>::fail({ ErrorCode::NotFound,
            "manifest.json not found: " + manifestPath });
    std::ostringstream buf;
    buf << in.rdbuf();
    return loadManifestFromString(buf.str(), extensionId);
}

}  // namespace ng
